title: Mu-Ting Huang # your name (or website title) here
logo: "/images/Pphoto.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Budget Analyst 
  <br><br>
  
  Linkedin
  <br>
  <a href="https://www.linkedin.com/in/mutinghuang/">View My LinkedIn Profile</a> 
  <br><br>
  CV
  <br>
  <a href="https://alex31425.github.io/online-cv/">View My online CV</a>
  <br><br>
  <a href="https://alex31425.github.io/MTHuang/Python_Basics_Cheat_Sheets">Python Basics & Cheat Sheets</a>
  <b>Exploratory Data Analysis</b>
  <br>
  - <a href="https://alex31425.github.io/MTHuang/sample_page">Data Normalization for Numeric features</a>
  <br>
  - <a href="https://medium.com/analytics-vidhya/detecting-outliers-using-box-and-whisker-diagrams-and-iqr-346a1b9c0dbe">Outliers</a>
  <br>
  <b>Feature Selection & Engineering</b>
  <br>
  - <a href="https://towardsdatascience.com/the-art-of-finding-the-best-features-for-machine-learning-a9074e2ca60d">The Art of Finding the Best Features for Machine Learning</a>
  <br>
  <b>Evaluation Metrics Machine Learning</b>
  <br>
  - <a href="https://towardsdatascience.com/understanding-the-confusion-matrix-and-its-business-applications-c4e8aaf37f42">Confusion Matrix</a>
  <br>
  - <a href="https://towardsdatascience.com/understanding-auc-roc-curve-68b2303cc9c5">AUC - ROC Curve</a>
  <br>
  <a href="https://alex31425.github.io/MTHuang/Machine_Learning_models">Machine Learning Models</a>
  <br>
  <b>Project</b>
  <br>
  - <a href="https://github.com/alex31425/BDA696-MuTing/wiki">Machine Learning Engineering for Predicting Major League Baseball Team Wins</a>
  <br>
  - <a href="https://sites.google.com/sdsu.edu/bda594bairbnbanalysis/home">Analysis of Airbnb Lodging Service in San Diego</a>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
